'use client';

import { useEffect, useState } from 'react';
import { Printer, Download, ArrowLeft, ShieldCheck, Heart, Activity } from 'lucide-react';
import Link from 'next/link';
import { getProfile } from '@/lib/storage';
import { LifeSignalProfile } from '@/lib/types';

export default function ShareDoctorPage() {
    const [profile, setProfile] = useState<LifeSignalProfile | null>(null);

    useEffect(() => {
        setProfile(getProfile());
    }, []);

    if (!profile) return null;

    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="min-h-screen bg-white text-black font-sans pb-20 print:pb-0">
            {/* TOOLBAR - HIDDEN ON PRINT */}
            <div className="bg-[#f5f5f5] border-b border-gray-200 py-4 px-6 sticky top-0 z-10 print:hidden">
                <div className="max-w-3xl mx-auto flex items-center justify-between">
                    <Link href="/vault" className="flex items-center gap-2 text-sm font-bold text-gray-500 hover:text-black transition-colors">
                        <ArrowLeft size={16} /> Dashboard
                    </Link>
                    <div className="flex gap-4">
                        <button
                            onClick={handlePrint}
                            className="bg-black text-white px-5 py-2 rounded-lg text-xs font-black uppercase tracking-widest flex items-center gap-2 hover:bg-gray-800 transition-all active:scale-95"
                        >
                            <Printer size={16} /> Print Summary
                        </button>
                    </div>
                </div>
            </div>

            <div className="max-w-3xl mx-auto px-10 py-16 space-y-12 print:py-0 print:px-0">

                {/* CLINICAL HEADER */}
                <div className="flex justify-between items-start border-b-4 border-black pb-8">
                    <div className="space-y-1">
                        <h1 className="text-4xl font-black tracking-tight uppercase">Medical Health Summary</h1>
                        <p className="text-sm font-bold text-gray-500 tracking-widest uppercase">Generated by Life Vault • {new Date().toLocaleDateString()}</p>
                    </div>
                    <div className="h-16 w-16 bg-black flex items-center justify-center text-white text-3xl font-black">✚</div>
                </div>

                {/* PATIENT INFO */}
                <div className="grid grid-cols-3 gap-12">
                    <div className="col-span-2 space-y-6">
                        <SectionTitle title="Patient Identity" />
                        <div className="grid grid-cols-2 gap-8">
                            <div>
                                <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest block mb-1">Full Name</label>
                                <p className="text-xl font-bold">{profile.fullName}</p>
                            </div>
                            <div>
                                <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest block mb-1">Blood Group</label>
                                <p className="text-xl font-bold underline decoration-2">{profile.bloodGroup}</p>
                            </div>
                        </div>
                    </div>
                    <div className="bg-gray-50 p-6 rounded-xl border border-gray-100">
                        <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest block mb-2">Vault Identity</label>
                        <p className="text-[10px] font-mono break-all font-bold">{profile.id}</p>
                        <div className="mt-4 pt-4 border-t border-gray-200">
                            <p className="text-[10px] font-black uppercase text-gray-400">Status</p>
                            <p className="text-xs font-bold text-emerald-600 uppercase">Verified Local Profile</p>
                        </div>
                    </div>
                </div>

                {/* CLINICAL SUMMARY GRID */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-16">
                    <div className="space-y-8">
                        <div className="space-y-4">
                            <SectionTitle title="Critical Allergies" />
                            {profile.allergies.split(',').filter(Boolean).length > 0 ? (
                                <ul className="space-y-2 list-disc pl-5">
                                    {profile.allergies.split(',').map((a, i) => (
                                        <li key={i} className="text-md font-bold text-rose-600">{a.trim()}</li>
                                    ))}
                                </ul>
                            ) : <p className="text-gray-400 italic">None reported.</p>}
                        </div>

                        <div className="space-y-4">
                            <SectionTitle title="Chronic Conditions" />
                            {profile.conditions.split(',').filter(Boolean).length > 0 ? (
                                <ul className="space-y-2 list-disc pl-5">
                                    {profile.conditions.split(',').map((c, i) => (
                                        <li key={i} className="text-md font-bold">{c.trim()}</li>
                                    ))}
                                </ul>
                            ) : <p className="text-gray-400 italic">None reported.</p>}
                        </div>
                    </div>

                    <div className="space-y-8">
                        <div className="space-y-4">
                            <SectionTitle title="Current Medications" />
                            {profile.medications.split(',').filter(Boolean).length > 0 ? (
                                <ul className="space-y-2 list-disc pl-5">
                                    {profile.medications.split(',').map((m, i) => (
                                        <li key={i} className="text-md font-bold">{m.trim()}</li>
                                    ))}
                                </ul>
                            ) : <p className="text-gray-400 italic">None reported.</p>}
                        </div>

                        {profile.diabetesProfile?.hasDiabetes && (
                            <div className="space-y-4 bg-gray-50 p-6 rounded-xl border border-gray-100">
                                <SectionTitle title="Diabetes Profile" />
                                <div className="grid grid-cols-2 gap-4 mt-4">
                                    <div>
                                        <p className="text-[10px] uppercase font-bold text-gray-400">Type</p>
                                        <p className="text-sm font-black">{profile.diabetesProfile.type}</p>
                                    </div>
                                    <div>
                                        <p className="text-[10px] uppercase font-bold text-gray-400">Insulin</p>
                                        <p className="text-sm font-black">{profile.diabetesProfile.insulinDependent ? 'Dependent' : 'Non-Dependent'}</p>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* VITAL HISTORY (LAST 10) */}
                <div className="space-y-6">
                    <SectionTitle title="Recent Blood Glucose Logs" />
                    <div className="border border-gray-200 rounded-xl overflow-hidden">
                        <table className="w-full text-left text-sm">
                            <thead>
                                <tr className="bg-gray-50 border-b border-gray-200">
                                    <th className="px-6 py-3 font-black uppercase text-[10px]">Date & Time</th>
                                    <th className="px-6 py-3 font-black uppercase text-[10px]">Reading</th>
                                    <th className="px-6 py-3 font-black uppercase text-[10px]">Status</th>
                                    <th className="px-6 py-3 font-black uppercase text-[10px]">Notes</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-100">
                                {(profile.vitalHistory || []).filter(v => v.type === 'blood_sugar').slice(0, 10).map((v) => {
                                    const val = parseInt(v.value);
                                    const status = val > 140 ? 'High' : val < 70 ? 'Low' : 'Normal';
                                    return (
                                        <tr key={v.id}>
                                            <td className="px-6 py-4 font-mono text-[11px]">{new Date(v.recordedAt).toLocaleString()}</td>
                                            <td className="px-6 py-4 font-black">{v.value} mg/dL</td>
                                            <td className={`px-6 py-4 font-bold text-xs uppercase ${status === 'Normal' ? 'text-emerald-600' : 'text-amber-600'}`}>{status}</td>
                                            <td className="px-6 py-4 text-gray-500 italic">{v.note || '-'}</td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                </div>

                {/* CONTACT INFO */}
                <div className="grid grid-cols-2 gap-12 pt-8 border-t border-gray-200">
                    <div className="space-y-4">
                        <SectionTitle title="Emergency Contact (ICE)" />
                        <div>
                            <p className="text-lg font-black">{profile.emergencyContact.name}</p>
                            <p className="text-xs font-mono font-bold text-gray-500">{profile.emergencyContact.phone}</p>
                            <p className="text-[10px] uppercase font-bold text-gray-400 mt-1">Primary Emergency Contact</p>
                        </div>
                    </div>
                    {profile.personalDoctor && (
                        <div className="space-y-4">
                            <SectionTitle title="Personal Physician" />
                            <div>
                                <p className="text-lg font-black">{profile.personalDoctor.name}</p>
                                <p className="text-xs font-bold">{profile.personalDoctor.hospital} · {profile.personalDoctor.phone}</p>
                                <p className="text-[10px] uppercase font-bold text-gray-400 mt-1">Primary Care Provider</p>
                            </div>
                        </div>
                    )}
                </div>

                {/* FOOTER */}
                <footer className="pt-24 pb-8 text-center space-y-4 opacity-40 print:pt-12">
                    <div className="flex items-center justify-center gap-2 mb-2">
                        <ShieldCheck size={14} />
                        <p className="text-[10px] font-black uppercase">Clinically Verified Local Identity</p>
                    </div>
                    <p className="text-[9px] max-w-md mx-auto leading-relaxed">
                        This document was generated locally by the Life Vault application. All medical data is stored on the user's device and has not been verified by a central authority. For clinical decisions, please verify with the patient and primary care provider.
                    </p>
                </footer>

            </div>

            <style jsx global>{`
        @media print {
          body { background-color: white !important; }
          .min-h-screen { min-height: auto !important; }
        }
      `}</style>
        </div>
    );
}

function SectionTitle({ title }: { title: string }) {
    return (
        <div className="flex items-center gap-2">
            <div className="h-2 w-2 bg-black rounded-full"></div>
            <h2 className="text-xs font-black uppercase tracking-widest text-black">{title}</h2>
        </div>
    );
}
